name: 🐛 Bug Report
description: Report a bug
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: Step-by-step reproduction
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
